### ISSUE TITLE
Remove NO-BREAK SPACE

### ISSUE THREAD

**Issue by TomazErjavec** [COST-ELTeC/ELTeC-rom#2]
In the level1 novels there are many U+00A0 NO-BREAK SPACE charactes - as ELTeC is not interested in typography, and as linguistic annotation tools often have problems with this character, I suggest to change them to ordinary space.

**Comment by RoxanaPatras** [comment]
pls, give me an example. 
Before removing them, let's check code - maybe it comes from UTF-8Y

**Comment by TomazErjavec** [comment]
Ups, sorry, for some reason I don't get mails from your comments, so I already fixed this, I think ti is ok.
