### ISSUE TITLE
Remove leading/trailing spaces

### ISSUE THREAD

**Issue by TomazErjavec** [COST-ELTeC/ELTeC-rom#3]
In level1 there are lots of cases where an element containing text begins and/or ends with a space, e.g.
`<title> Geniu Pustiu : ediție ELTeC </title>` or `<p> Boerul nici nu cercetă nimic.</p>`. For nicer presentation, better meta-data, and easier linguistic processing, I suggest these leading and trailing spaces be removed.

**Comment by RoxanaPatras** [comment]
agreed. it's from manual correction
