### ISSUE TITLE
APOSTROPHE or RIGHT SINGLE QUOTATION MARK?

### ISSUE THREAD

**Issue by TomazErjavec** [COST-ELTeC/ELTeC-rom#4]
In level1 both U+0027 APOSTROPHE (') and U+2019 RIGHT SINGLE QUOTATION MARK (’) are used for contractions, such as in ROM002:
```<l>N'am ce spune, n’am ce zice.</l>```

I propose to unify this to one character. @RoxanaPatras, can you pls. let me know:

* which of the two characters I should use (I think apostrophe, like in English, but am not sure)
* is it true that neither character is used in a different context than for contractions (i.e. neither is use to delimit quoted speech or similar)?

**Comment by RoxanaPatras** [comment]
It's from inconsistent manual correction. 
Indeed they mark contraction. Both types of apostrophe should be replaced with "-"
If I make a short list of typo fixes (e.g. "ó" = "oa"; "ȡ" = "z"), could you insert them in the script?

**Comment by RoxanaPatras** [comment]
or, could we use that? 
https://github.com/racai-ai/TEPROLIN/blob/master/PyTEPRO.py

**Comment by TomazErjavec** [comment]
> Indeed they mark contraction. Both types of apostrophe should be replaced with "-"

OK, I did this, as well as lots of other fixes - pls. pull the new version.

> If I make a short list of typo fixes (e.g. "ó" = "oa"; "ȡ" = "z"), could you insert them in the script?

Yes, I will open another issue for that.

> could we use that? https://github.com/racai-ai/TEPROLIN/blob/master/PyTEPRO.py

Not me, it looks scary!
