### ISSUE TITLE
files too big for UDpipe

### ISSUE THREAD

**Issue by RoxanaPatras** [COST-ELTeC/ELTeC-rom#6]
ROM025, ROM 056, ROM076, ROM077, ROM078, ROM095. 
What's the best solution to get them parsed and tokenized?

**Comment by TomazErjavec** [comment]
Split them into two and process each part separately, then join? 
Given that there are only a few, it should be too hard.

**Comment by RoxanaPatras** [comment]
did so. Don't know how to merge them, I suppose they can be merged after they are turned into xml-s

**Comment by TomazErjavec** [comment]
No, they have to be merged in CoNLLU. I can do it if you put then in the conll directory, with appropriate suffixes, like ROM025-1, ROM025-2 etc.

**Comment by RoxanaPatras** [comment]
Done

**Comment by TomazErjavec** [comment]
OK, closing for now.
