### ISSUE TITLE
opening and checking CoNLL-U files

### ISSUE THREAD

**Issue by RoxanaPatras** [COST-ELTeC/ELTeC-rom#7]
I'd like to check twice if I saved and named properly the files. The only thing I could do is to change extension into csv and open them with an editor. Do you think I should do that or is there any other way to check automatically if the txt file corresponds to the conllu file?

**Comment by TomazErjavec** [comment]
This will be done when merging conll files with the original TEI ones - the program dies if it doesn't find the text it expects.
