### ISSUE TITLE
create directory 

### ISSUE THREAD

**Issue by RoxanaPatras** [COST-ELTeC/ELTeC-rom#8]
Still it seems that I'm not able to create a new directory under stats. I can only create new directories under COST-ELTeC.

**Comment by TomazErjavec** [comment]
> Still it seems that I'm not able to create a new directory under stats. 

If you are able to upload files, you are able to create directories. So I think you must be doing something wrong. But you don't write what the error is, so I can't really help.

Anyway I now (in [69be019](https://github.com/COST-ELTeC/ELTeC-rom/commit/69be019467b8059b3c7b7fd67e2503f3fc7b0458)) moved the files to the [scripts/conll](https://github.com/COST-ELTeC/ELTeC-rom/tree/master/scripts/conll) directory, so you don't actually need to make a new directory.

> I can only create new directories under COST-ELTeC.

Um, COST-ELTeC is a virtual organisation, you can't create directories there, you can only create new git projects.
